### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [rewaza/shortpath#1]
Please remove https://github.com/rewaza/shortpath/tree/main/__pycache__ and any .pyc files they are auto generated on install.

When done please update the zip to qgis plugin repo

**Comment by rewaza** [comment]
Hello,
I removed the pycache directory and all .pyc files from github.
The Abovementioned folder and .pyc files weren't in the uploaded archive as
I removed them before upload.
Please, let me know if any changes are needed.
Thank you in advance.
Regards,
Revaz
